### PR TITLE
Feat/add ansible role

### PR DESCRIPTION
**Pull request by durduliu2009**
Create ansible role which will deploy iredmail/mariadb:nightly image on a dedicated machine via ssh
Documentation can be improved in time with your help.

### CODE REVIEW

**Comment by iredmail** [comment]
Cool.

But i prefer keeping this repo clean. Would you like to create a separated GitHub repo for your ansible playbooks? I'm more than happy to add link to your repo in the README.md file. :)

**Comment by durduliu2009** [comment]
Ok I will create a new repo with only ansible playbook(s) without this fork which I will delete
I will come back with a link

**Comment by iredmail** [comment]
Awesome. Reply here when your repo is ready. :)

**Comment by iredmail** [comment]
Would you like to rename your github repo to be clearer? For example, `ansible-dockerized-iredmail`. Current repo name `ansible-roles` is not clear at all.

**Comment by durduliu2009** [comment]
Nope because there will be more opensource projects like 
ansible-roles/iRedMail or ansible-roles/iredmail/dockerized
ansible-roles/rancher-rke
ansible-roles/other-project...

I don't want to create a separate repo foreach project because will be so hard for me to maintain since I'm using also gitlab in some use cases ...

**Comment by iredmail** [comment]
This sounds a pretty bad practice to me.

For yourself, it's ok to put all ansible related projects in one repo, but could you put ansible code for dockerized iRedMail in a separated repo?

**Comment by durduliu2009** [comment]
Ok. I will create a separate repo for that

**Comment by durduliu2009** [comment]
https://github.com/durduliu2009/ansible-dockerized-iredmail -> I hope that now is ok

**Comment by iredmail** [comment]
Few issues with your Ansible code:

- You use hard-coded path names for volumes (e.g. `/iredmail/data/backup:...`), should use the `VOLUMES_PATH` variable name (e.g. `{{ VOLUMES_PATH }}/backup`). https://github.com/ricristian/ansible-dockerized-iredmail/blob/00abf9b5f6cbd4db33d07b4af95404b35b294b87/all-in-one/tasks/main.yml#L38
- Variable name `VOLUMES_PATH` is not accurate. Better rename it to something like `IREDMAIL_DATA_DIR`. https://github.com/ricristian/ansible-dockerized-iredmail/blob/00abf9b5f6cbd4db33d07b4af95404b35b294b87/all-in-one/tasks/main.yml#L4

**Comment by ricristian** [comment]
Yes you're right :) 
Updated with your suggestion. Thank you !

**Pull request closed without merging**
